version: "3.5"

services:
  node:
    container_name: logsapi.node
    image: node:16
    restart: unless-stopped
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    working_dir: /app
    command: node index.js
    ports:
      - ${NODE_LISTEN:-127.0.0.1:3000:3000}

  munin-node:
    image: darioguarascio/munin-node:latest
    container_name: virail.mapping.munin-node
    privileged: true
    restart: "always"
    environment:
      MUNIN_ALLOW: ${MUNIN_ALLOW:-0.0.0.0/0}
      MUNIN_ENABLED_PLUGINS: ${MUNIN_ENABLED_PLUGINS:-traffic cpu df netstat system* load memory uptime}
      # MUNIN_LINKED_PLUGINS: ${MUNIN_LINKED_PLUGINS:-}
    volumes:
      - /tmp/munin-node:/data
    ports:
      - ${MUNIN_LISTEN:-127.0.0.1:4949}:4949
    env_file:
      - ${MUNIN_ENV_FILE:-.env}
