version: "3.5"

services:
  node:
    container_name: logsapi.node
    image: node:16
    restart: unless-stopped
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    working_dir: /app
    command: node index.js
    ports:
      - ${NODE_LISTEN:-127.0.0.1:3000:3000}

